// Code generated by tools/update-providers.go; DO NOT EDIT.
package handler

func ProvideBlocksHandler() BlocksHandler {
	return &blocksHandlerImpl{}
}

func ProvideIspHandler() IspHandler {
	return &ispHandlerImpl{}
}

func ProvideSitesHandler() SitesHandler {
	return &sitesHandlerImpl{}
}
