// Code generated by tools/update-providers.go; DO NOT EDIT.
package handler

import "github.com/gnulinuxindia/internet-chowkidar/pkg/domain/service"

func ProvideCounterHandler(
	counterService service.CounterService,
) CounterHandler {
	return &counterHandlerImpl{
		counterService: counterService,
	}
}
