// Code generated by tools/update-providers.go; DO NOT EDIT.
package handler

import "github.com/gnulinuxindia/internet-chowkidar/pkg/domain/service"

func ProvideBlocksHandler() BlocksHandler {
	return &blocksHandlerImpl{}
}

func ProvideIspHandler() IspHandler {
	return &ispHandlerImpl{}
}

func ProvideReportsHandler() ReportsHandler {
	return &reportsHandlerImpl{}
}

func ProvideSitesHandler(
	sitesService service.SitesService,
) SitesHandler {
	return &sitesHandlerImpl{
		sitesService: sitesService,
	}
}
