// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/gnulinuxindia/internet-chowkidar/api"
	"github.com/gnulinuxindia/internet-chowkidar/api/handler"
	"github.com/gnulinuxindia/internet-chowkidar/ent"
	"github.com/gnulinuxindia/internet-chowkidar/internal/config"
	"github.com/gnulinuxindia/internet-chowkidar/internal/db"
	"github.com/gnulinuxindia/internet-chowkidar/internal/tracing"
	"github.com/gnulinuxindia/internet-chowkidar/pkg/domain/provider"
	"github.com/gnulinuxindia/internet-chowkidar/pkg/domain/repository"
	"github.com/gnulinuxindia/internet-chowkidar/pkg/domain/service"
	"github.com/google/wire"
	"go.opentelemetry.io/otel/sdk/trace"
	"go.uber.org/mock/gomock"
)

// Injectors from wire.go:

// handlers
func InjectHandlers() (*api.Handlers, error) {
	blocksHandler := handler.ProvideBlocksHandler()
	categoryHandler := handler.ProvideCategoryHandler()
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideRawDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := db.ProvideDB(sqlDB, configConfig)
	if err != nil {
		return nil, err
	}
	ispRepository := repository.ProvideIspRepository(client)
	ispService := service.ProvideIspService(ispRepository)
	ispHandler := handler.ProvideIspHandler(ispService)
	reportsHandler := handler.ProvideReportsHandler()
	sitesRepository := repository.ProvideSitesRepository(client)
	sitesService := service.ProvideSitesService(sitesRepository)
	sitesHandler := handler.ProvideSitesHandler(sitesService)
	handlers := &api.Handlers{
		BlocksHandler:   blocksHandler,
		CategoryHandler: categoryHandler,
		IspHandler:      ispHandler,
		ReportsHandler:  reportsHandler,
		SitesHandler:    sitesHandler,
	}
	return handlers, nil
}

func InjectMockHandlers(ctrl *gomock.Controller) (*api.Handlers, error) {
	blocksHandler := handler.ProvideBlocksHandler()
	categoryHandler := handler.ProvideCategoryHandler()
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideRawDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := db.ProvideDB(sqlDB, configConfig)
	if err != nil {
		return nil, err
	}
	ispRepository := repository.ProvideIspRepository(client)
	ispService := service.ProvideIspService(ispRepository)
	ispHandler := handler.ProvideIspHandler(ispService)
	reportsHandler := handler.ProvideReportsHandler()
	sitesRepository := repository.ProvideSitesRepository(client)
	sitesService := service.ProvideSitesService(sitesRepository)
	sitesHandler := handler.ProvideSitesHandler(sitesService)
	handlers := &api.Handlers{
		BlocksHandler:   blocksHandler,
		CategoryHandler: categoryHandler,
		IspHandler:      ispHandler,
		ReportsHandler:  reportsHandler,
		SitesHandler:    sitesHandler,
	}
	return handlers, nil
}

// services
func InjectServices() (*di.Services, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideRawDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := db.ProvideDB(sqlDB, configConfig)
	if err != nil {
		return nil, err
	}
	ispRepository := repository.ProvideIspRepository(client)
	ispService := service.ProvideIspService(ispRepository)
	sitesRepository := repository.ProvideSitesRepository(client)
	sitesService := service.ProvideSitesService(sitesRepository)
	services := &di.Services{
		IspService:   ispService,
		SitesService: sitesService,
	}
	return services, nil
}

func InjectMockServices(ctrl *gomock.Controller) (*di.Services, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideRawDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := db.ProvideDB(sqlDB, configConfig)
	if err != nil {
		return nil, err
	}
	ispRepository := repository.ProvideIspRepository(client)
	ispService := service.ProvideIspService(ispRepository)
	sitesRepository := repository.ProvideSitesRepository(client)
	sitesService := service.ProvideSitesService(sitesRepository)
	services := &di.Services{
		IspService:   ispService,
		SitesService: sitesService,
	}
	return services, nil
}

// repositories
func InjectRepository() (*di.Repositories, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideRawDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := db.ProvideDB(sqlDB, configConfig)
	if err != nil {
		return nil, err
	}
	blocksRepository := repository.ProvideBlocksRepository(client)
	counterRepository := repository.ProvideCounterRepository(client)
	ispRepository := repository.ProvideIspRepository(client)
	reportsRepository := repository.ProvideReportsRepository(client)
	sitesRepository := repository.ProvideSitesRepository(client)
	repositories := &di.Repositories{
		BlocksRepository:  blocksRepository,
		CounterRepository: counterRepository,
		IspRepository:     ispRepository,
		ReportsRepository: reportsRepository,
		SitesRepository:   sitesRepository,
	}
	return repositories, nil
}

func InjectMockRepository(ctrl *gomock.Controller) (*di.Repositories, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideRawDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := db.ProvideDB(sqlDB, configConfig)
	if err != nil {
		return nil, err
	}
	blocksRepository := repository.ProvideBlocksRepository(client)
	counterRepository := repository.ProvideCounterRepository(client)
	ispRepository := repository.ProvideIspRepository(client)
	reportsRepository := repository.ProvideReportsRepository(client)
	sitesRepository := repository.ProvideSitesRepository(client)
	repositories := &di.Repositories{
		BlocksRepository:  blocksRepository,
		CounterRepository: counterRepository,
		IspRepository:     ispRepository,
		ReportsRepository: reportsRepository,
		SitesRepository:   sitesRepository,
	}
	return repositories, nil
}

// misc
func InjectDb() (*ent.Client, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideRawDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := db.ProvideDB(sqlDB, configConfig)
	if err != nil {
		return nil, err
	}
	return client, nil
}

func InjectMockDb() (*ent.Client, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideRawDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := db.ProvideDB(sqlDB, configConfig)
	if err != nil {
		return nil, err
	}
	return client, nil
}

func InjectTracerProvider() (*trace.TracerProvider, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	tracerProvider, err := tracing.ProvideTracerProvider(configConfig)
	if err != nil {
		return nil, err
	}
	return tracerProvider, nil
}

func InjectRawDb() (*sql.DB, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideRawDB(configConfig)
	if err != nil {
		return nil, err
	}
	return sqlDB, nil
}

func InjectConfig() (*config.Config, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	return configConfig, nil
}

func InjectTxHandler() (*repository.TxHandler, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideRawDB(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := db.ProvideDB(sqlDB, configConfig)
	if err != nil {
		return nil, err
	}
	txHandler := repository.NewTxHandler(client)
	return txHandler, nil
}

// wire.go:

var dbSet = wire.NewSet(db.ProvideDB, db.ProvideRawDB, config.ProvideConfig)

var mockDbSet = wire.NewSet(db.ProvideDB, db.ProvideRawDB, config.ProvideConfig)

var concreteSet = wire.NewSet(api.HandlerSet, di.RepositorySet, di.ServiceSet)

var mockSet = wire.NewSet(api.MockHandlerSet, di.MockRepositorySet, di.MockServiceSet)

var tracingSet = wire.NewSet(config.ProvideConfig, tracing.ProvideTracerProvider)
