database_url: ENC[AES256_GCM,data:gRUCwLtSWcXxzDQWzdMpeg7I9QZFHVgWS+X4lLIG19GzX6Jj9k+3ePGcWhaNTVhctKpL4d8r7mg=,iv:w7Ba0ziKp7WggbcOiKxJKYJla6G2X1Ef+EuW0KTFreA=,tag:/fDPkDSdUsYbGq4ZWGJJBg==,type:str]
api_key: ENC[AES256_GCM,data:5UBvbdU1zT8UbwqC,iv:UXsRtOnoYTU+QzR8wGvll+9+fub3mRxADU/ConjDHz8=,tag:mZF4nl18JejHR0cZXKpsFA==,type:str]
sops:
    age:
        - recipient: age1dlhx6mhd8h3gg9mxmf3tptrx2gcn3ee4jp7evnlxhuezmfj0qd2sf0q7lp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYk5KMDQ1WTQ5SHNjSVNN
            Q0JUeGh3OEpFNTMrRGRZVUJBTmdTbDl4YlE0CkxCNzZCT2dWRkRINDN5R0VJbkRs
            dldiM2xTR1dCaWQzdVdUSEh2UkhFSTgKLS0tIGlTNWFPSGpkYjBzcVFRalNqNWp2
            dmlvaG9JLzdmOXZoQjUvVWVISTFVbFUKwaj8YrvUEHBN6/jdfgIhJGTvLzXPp2I8
            y6vb08vVQTDsmwD/UwYutDeJBqzwGzN2yf9UBk2LZcR+mAZgRCwxYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T17:43:46Z"
    mac: ENC[AES256_GCM,data:5JJJE+ec3FexIhUgsxy/WI/cVA+2j0yonYlXn27/GWzavAVOGnXvzKvjS7Pn7MWxpZ38o2Il+emzXYLUYQJlZQlm8+UasDB2Q1jMRTyTNZmmq8dZ+3bgu8OKiF4Xlu3KR74NSporLmdZfI4csNpaN6+jCT6hUaR1lTVAf8zrnsk=,iv:tzZ5YQg/MLhm8y2N5+JYNVNYcGP7rBu3Wfa8Sd+69Lg=,tag:MByafIyxXWxNm8GfeZbXFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
