// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gnulinuxindia/internet-chowkidar/ent/blocks"
	"github.com/gnulinuxindia/internet-chowkidar/ent/isps"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sites"
)

// BlocksCreate is the builder for creating a Blocks entity.
type BlocksCreate struct {
	config
	mutation *BlocksMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (bc *BlocksCreate) SetCreatedAt(t time.Time) *BlocksCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BlocksCreate) SetNillableCreatedAt(t *time.Time) *BlocksCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BlocksCreate) SetUpdatedAt(t time.Time) *BlocksCreate {
	bc.mutation.SetUpdatedAt(t)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BlocksCreate) SetNillableUpdatedAt(t *time.Time) *BlocksCreate {
	if t != nil {
		bc.SetUpdatedAt(*t)
	}
	return bc
}

// SetSiteID sets the "site_id" field.
func (bc *BlocksCreate) SetSiteID(i int) *BlocksCreate {
	bc.mutation.SetSiteID(i)
	return bc
}

// SetIspID sets the "isp_id" field.
func (bc *BlocksCreate) SetIspID(i int) *BlocksCreate {
	bc.mutation.SetIspID(i)
	return bc
}

// SetBlockReports sets the "block_reports" field.
func (bc *BlocksCreate) SetBlockReports(i int) *BlocksCreate {
	bc.mutation.SetBlockReports(i)
	return bc
}

// SetNillableBlockReports sets the "block_reports" field if the given value is not nil.
func (bc *BlocksCreate) SetNillableBlockReports(i *int) *BlocksCreate {
	if i != nil {
		bc.SetBlockReports(*i)
	}
	return bc
}

// SetUnblockReports sets the "unblock_reports" field.
func (bc *BlocksCreate) SetUnblockReports(i int) *BlocksCreate {
	bc.mutation.SetUnblockReports(i)
	return bc
}

// SetNillableUnblockReports sets the "unblock_reports" field if the given value is not nil.
func (bc *BlocksCreate) SetNillableUnblockReports(i *int) *BlocksCreate {
	if i != nil {
		bc.SetUnblockReports(*i)
	}
	return bc
}

// SetLastReportedAt sets the "last_reported_at" field.
func (bc *BlocksCreate) SetLastReportedAt(t time.Time) *BlocksCreate {
	bc.mutation.SetLastReportedAt(t)
	return bc
}

// SetSite sets the "site" edge to the Sites entity.
func (bc *BlocksCreate) SetSite(s *Sites) *BlocksCreate {
	return bc.SetSiteID(s.ID)
}

// SetIsp sets the "isp" edge to the Isps entity.
func (bc *BlocksCreate) SetIsp(i *Isps) *BlocksCreate {
	return bc.SetIspID(i.ID)
}

// Mutation returns the BlocksMutation object of the builder.
func (bc *BlocksCreate) Mutation() *BlocksMutation {
	return bc.mutation
}

// Save creates the Blocks in the database.
func (bc *BlocksCreate) Save(ctx context.Context) (*Blocks, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BlocksCreate) SaveX(ctx context.Context) *Blocks {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BlocksCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BlocksCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BlocksCreate) defaults() {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := blocks.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		v := blocks.DefaultUpdatedAt()
		bc.mutation.SetUpdatedAt(v)
	}
	if _, ok := bc.mutation.BlockReports(); !ok {
		v := blocks.DefaultBlockReports
		bc.mutation.SetBlockReports(v)
	}
	if _, ok := bc.mutation.UnblockReports(); !ok {
		v := blocks.DefaultUnblockReports
		bc.mutation.SetUnblockReports(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BlocksCreate) check() error {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Blocks.created_at"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Blocks.updated_at"`)}
	}
	if _, ok := bc.mutation.SiteID(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "Blocks.site_id"`)}
	}
	if _, ok := bc.mutation.IspID(); !ok {
		return &ValidationError{Name: "isp_id", err: errors.New(`ent: missing required field "Blocks.isp_id"`)}
	}
	if _, ok := bc.mutation.BlockReports(); !ok {
		return &ValidationError{Name: "block_reports", err: errors.New(`ent: missing required field "Blocks.block_reports"`)}
	}
	if _, ok := bc.mutation.UnblockReports(); !ok {
		return &ValidationError{Name: "unblock_reports", err: errors.New(`ent: missing required field "Blocks.unblock_reports"`)}
	}
	if _, ok := bc.mutation.LastReportedAt(); !ok {
		return &ValidationError{Name: "last_reported_at", err: errors.New(`ent: missing required field "Blocks.last_reported_at"`)}
	}
	if _, ok := bc.mutation.SiteID(); !ok {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "Blocks.site"`)}
	}
	if _, ok := bc.mutation.IspID(); !ok {
		return &ValidationError{Name: "isp", err: errors.New(`ent: missing required edge "Blocks.isp"`)}
	}
	return nil
}

func (bc *BlocksCreate) sqlSave(ctx context.Context) (*Blocks, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BlocksCreate) createSpec() (*Blocks, *sqlgraph.CreateSpec) {
	var (
		_node = &Blocks{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(blocks.Table, sqlgraph.NewFieldSpec(blocks.FieldID, field.TypeInt))
	)
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(blocks.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.SetField(blocks.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := bc.mutation.BlockReports(); ok {
		_spec.SetField(blocks.FieldBlockReports, field.TypeInt, value)
		_node.BlockReports = value
	}
	if value, ok := bc.mutation.UnblockReports(); ok {
		_spec.SetField(blocks.FieldUnblockReports, field.TypeInt, value)
		_node.UnblockReports = value
	}
	if value, ok := bc.mutation.LastReportedAt(); ok {
		_spec.SetField(blocks.FieldLastReportedAt, field.TypeTime, value)
		_node.LastReportedAt = value
	}
	if nodes := bc.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blocks.SiteTable,
			Columns: []string{blocks.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bc.mutation.IspIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   blocks.IspTable,
			Columns: []string{blocks.IspColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(isps.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IspID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BlocksCreateBulk is the builder for creating many Blocks entities in bulk.
type BlocksCreateBulk struct {
	config
	err      error
	builders []*BlocksCreate
}

// Save creates the Blocks entities in the database.
func (bcb *BlocksCreateBulk) Save(ctx context.Context) ([]*Blocks, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Blocks, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlocksMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BlocksCreateBulk) SaveX(ctx context.Context) []*Blocks {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BlocksCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BlocksCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
