// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gnulinuxindia/internet-chowkidar/ent/categories"
	"github.com/gnulinuxindia/internet-chowkidar/ent/predicate"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sites"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sitescategories"
)

// CategoriesUpdate is the builder for updating Categories entities.
type CategoriesUpdate struct {
	config
	hooks    []Hook
	mutation *CategoriesMutation
}

// Where appends a list predicates to the CategoriesUpdate builder.
func (_u *CategoriesUpdate) Where(ps ...predicate.Categories) *CategoriesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CategoriesUpdate) SetUpdatedAt(v time.Time) *CategoriesUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CategoriesUpdate) SetName(v string) *CategoriesUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CategoriesUpdate) SetNillableName(v *string) *CategoriesUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddSiteIDs adds the "sites" edge to the Sites entity by IDs.
func (_u *CategoriesUpdate) AddSiteIDs(ids ...int) *CategoriesUpdate {
	_u.mutation.AddSiteIDs(ids...)
	return _u
}

// AddSites adds the "sites" edges to the Sites entity.
func (_u *CategoriesUpdate) AddSites(v ...*Sites) *CategoriesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSiteIDs(ids...)
}

// AddSitesCategoryIDs adds the "sites_categories" edge to the SitesCategories entity by IDs.
func (_u *CategoriesUpdate) AddSitesCategoryIDs(ids ...int) *CategoriesUpdate {
	_u.mutation.AddSitesCategoryIDs(ids...)
	return _u
}

// AddSitesCategories adds the "sites_categories" edges to the SitesCategories entity.
func (_u *CategoriesUpdate) AddSitesCategories(v ...*SitesCategories) *CategoriesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSitesCategoryIDs(ids...)
}

// Mutation returns the CategoriesMutation object of the builder.
func (_u *CategoriesUpdate) Mutation() *CategoriesMutation {
	return _u.mutation
}

// ClearSites clears all "sites" edges to the Sites entity.
func (_u *CategoriesUpdate) ClearSites() *CategoriesUpdate {
	_u.mutation.ClearSites()
	return _u
}

// RemoveSiteIDs removes the "sites" edge to Sites entities by IDs.
func (_u *CategoriesUpdate) RemoveSiteIDs(ids ...int) *CategoriesUpdate {
	_u.mutation.RemoveSiteIDs(ids...)
	return _u
}

// RemoveSites removes "sites" edges to Sites entities.
func (_u *CategoriesUpdate) RemoveSites(v ...*Sites) *CategoriesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSiteIDs(ids...)
}

// ClearSitesCategories clears all "sites_categories" edges to the SitesCategories entity.
func (_u *CategoriesUpdate) ClearSitesCategories() *CategoriesUpdate {
	_u.mutation.ClearSitesCategories()
	return _u
}

// RemoveSitesCategoryIDs removes the "sites_categories" edge to SitesCategories entities by IDs.
func (_u *CategoriesUpdate) RemoveSitesCategoryIDs(ids ...int) *CategoriesUpdate {
	_u.mutation.RemoveSitesCategoryIDs(ids...)
	return _u
}

// RemoveSitesCategories removes "sites_categories" edges to SitesCategories entities.
func (_u *CategoriesUpdate) RemoveSitesCategories(v ...*SitesCategories) *CategoriesUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSitesCategoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CategoriesUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CategoriesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CategoriesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CategoriesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CategoriesUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := categories.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CategoriesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(categories.Table, categories.Columns, sqlgraph.NewFieldSpec(categories.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(categories.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(categories.FieldName, field.TypeString, value)
	}
	if _u.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   categories.SitesTable,
			Columns: categories.SitesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSitesIDs(); len(nodes) > 0 && !_u.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   categories.SitesTable,
			Columns: categories.SitesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   categories.SitesTable,
			Columns: categories.SitesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SitesCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   categories.SitesCategoriesTable,
			Columns: []string{categories.SitesCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitescategories.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSitesCategoriesIDs(); len(nodes) > 0 && !_u.mutation.SitesCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   categories.SitesCategoriesTable,
			Columns: []string{categories.SitesCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitescategories.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SitesCategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   categories.SitesCategoriesTable,
			Columns: []string{categories.SitesCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitescategories.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{categories.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CategoriesUpdateOne is the builder for updating a single Categories entity.
type CategoriesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CategoriesMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CategoriesUpdateOne) SetUpdatedAt(v time.Time) *CategoriesUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CategoriesUpdateOne) SetName(v string) *CategoriesUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CategoriesUpdateOne) SetNillableName(v *string) *CategoriesUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddSiteIDs adds the "sites" edge to the Sites entity by IDs.
func (_u *CategoriesUpdateOne) AddSiteIDs(ids ...int) *CategoriesUpdateOne {
	_u.mutation.AddSiteIDs(ids...)
	return _u
}

// AddSites adds the "sites" edges to the Sites entity.
func (_u *CategoriesUpdateOne) AddSites(v ...*Sites) *CategoriesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSiteIDs(ids...)
}

// AddSitesCategoryIDs adds the "sites_categories" edge to the SitesCategories entity by IDs.
func (_u *CategoriesUpdateOne) AddSitesCategoryIDs(ids ...int) *CategoriesUpdateOne {
	_u.mutation.AddSitesCategoryIDs(ids...)
	return _u
}

// AddSitesCategories adds the "sites_categories" edges to the SitesCategories entity.
func (_u *CategoriesUpdateOne) AddSitesCategories(v ...*SitesCategories) *CategoriesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSitesCategoryIDs(ids...)
}

// Mutation returns the CategoriesMutation object of the builder.
func (_u *CategoriesUpdateOne) Mutation() *CategoriesMutation {
	return _u.mutation
}

// ClearSites clears all "sites" edges to the Sites entity.
func (_u *CategoriesUpdateOne) ClearSites() *CategoriesUpdateOne {
	_u.mutation.ClearSites()
	return _u
}

// RemoveSiteIDs removes the "sites" edge to Sites entities by IDs.
func (_u *CategoriesUpdateOne) RemoveSiteIDs(ids ...int) *CategoriesUpdateOne {
	_u.mutation.RemoveSiteIDs(ids...)
	return _u
}

// RemoveSites removes "sites" edges to Sites entities.
func (_u *CategoriesUpdateOne) RemoveSites(v ...*Sites) *CategoriesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSiteIDs(ids...)
}

// ClearSitesCategories clears all "sites_categories" edges to the SitesCategories entity.
func (_u *CategoriesUpdateOne) ClearSitesCategories() *CategoriesUpdateOne {
	_u.mutation.ClearSitesCategories()
	return _u
}

// RemoveSitesCategoryIDs removes the "sites_categories" edge to SitesCategories entities by IDs.
func (_u *CategoriesUpdateOne) RemoveSitesCategoryIDs(ids ...int) *CategoriesUpdateOne {
	_u.mutation.RemoveSitesCategoryIDs(ids...)
	return _u
}

// RemoveSitesCategories removes "sites_categories" edges to SitesCategories entities.
func (_u *CategoriesUpdateOne) RemoveSitesCategories(v ...*SitesCategories) *CategoriesUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSitesCategoryIDs(ids...)
}

// Where appends a list predicates to the CategoriesUpdate builder.
func (_u *CategoriesUpdateOne) Where(ps ...predicate.Categories) *CategoriesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CategoriesUpdateOne) Select(field string, fields ...string) *CategoriesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Categories entity.
func (_u *CategoriesUpdateOne) Save(ctx context.Context) (*Categories, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CategoriesUpdateOne) SaveX(ctx context.Context) *Categories {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CategoriesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CategoriesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CategoriesUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := categories.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CategoriesUpdateOne) sqlSave(ctx context.Context) (_node *Categories, err error) {
	_spec := sqlgraph.NewUpdateSpec(categories.Table, categories.Columns, sqlgraph.NewFieldSpec(categories.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Categories.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, categories.FieldID)
		for _, f := range fields {
			if !categories.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != categories.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(categories.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(categories.FieldName, field.TypeString, value)
	}
	if _u.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   categories.SitesTable,
			Columns: categories.SitesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSitesIDs(); len(nodes) > 0 && !_u.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   categories.SitesTable,
			Columns: categories.SitesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   categories.SitesTable,
			Columns: categories.SitesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SitesCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   categories.SitesCategoriesTable,
			Columns: []string{categories.SitesCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitescategories.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSitesCategoriesIDs(); len(nodes) > 0 && !_u.mutation.SitesCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   categories.SitesCategoriesTable,
			Columns: []string{categories.SitesCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitescategories.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SitesCategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   categories.SitesCategoriesTable,
			Columns: []string{categories.SitesCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitescategories.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Categories{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{categories.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
