// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gnulinuxindia/internet-chowkidar/ent/blocks"
	"github.com/gnulinuxindia/internet-chowkidar/ent/isps"
)

// IspsCreate is the builder for creating a Isps entity.
type IspsCreate struct {
	config
	mutation *IspsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *IspsCreate) SetCreatedAt(v time.Time) *IspsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IspsCreate) SetNillableCreatedAt(v *time.Time) *IspsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IspsCreate) SetUpdatedAt(v time.Time) *IspsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IspsCreate) SetNillableUpdatedAt(v *time.Time) *IspsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLatitude sets the "latitude" field.
func (_c *IspsCreate) SetLatitude(v float64) *IspsCreate {
	_c.mutation.SetLatitude(v)
	return _c
}

// SetLongitude sets the "longitude" field.
func (_c *IspsCreate) SetLongitude(v float64) *IspsCreate {
	_c.mutation.SetLongitude(v)
	return _c
}

// SetName sets the "name" field.
func (_c *IspsCreate) SetName(v string) *IspsCreate {
	_c.mutation.SetName(v)
	return _c
}

// AddIspBlockIDs adds the "isp_blocks" edge to the Blocks entity by IDs.
func (_c *IspsCreate) AddIspBlockIDs(ids ...int) *IspsCreate {
	_c.mutation.AddIspBlockIDs(ids...)
	return _c
}

// AddIspBlocks adds the "isp_blocks" edges to the Blocks entity.
func (_c *IspsCreate) AddIspBlocks(v ...*Blocks) *IspsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIspBlockIDs(ids...)
}

// Mutation returns the IspsMutation object of the builder.
func (_c *IspsCreate) Mutation() *IspsMutation {
	return _c.mutation
}

// Save creates the Isps in the database.
func (_c *IspsCreate) Save(ctx context.Context) (*Isps, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IspsCreate) SaveX(ctx context.Context) *Isps {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IspsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IspsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IspsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := isps.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := isps.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IspsCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Isps.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Isps.updated_at"`)}
	}
	if _, ok := _c.mutation.Latitude(); !ok {
		return &ValidationError{Name: "latitude", err: errors.New(`ent: missing required field "Isps.latitude"`)}
	}
	if _, ok := _c.mutation.Longitude(); !ok {
		return &ValidationError{Name: "longitude", err: errors.New(`ent: missing required field "Isps.longitude"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Isps.name"`)}
	}
	return nil
}

func (_c *IspsCreate) sqlSave(ctx context.Context) (*Isps, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IspsCreate) createSpec() (*Isps, *sqlgraph.CreateSpec) {
	var (
		_node = &Isps{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(isps.Table, sqlgraph.NewFieldSpec(isps.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(isps.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(isps.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Latitude(); ok {
		_spec.SetField(isps.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = value
	}
	if value, ok := _c.mutation.Longitude(); ok {
		_spec.SetField(isps.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(isps.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.IspBlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   isps.IspBlocksTable,
			Columns: []string{isps.IspBlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blocks.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IspsCreateBulk is the builder for creating many Isps entities in bulk.
type IspsCreateBulk struct {
	config
	err      error
	builders []*IspsCreate
}

// Save creates the Isps entities in the database.
func (_c *IspsCreateBulk) Save(ctx context.Context) ([]*Isps, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Isps, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IspsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IspsCreateBulk) SaveX(ctx context.Context) []*Isps {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IspsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IspsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
