// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gnulinuxindia/internet-chowkidar/ent/categories"
	"github.com/gnulinuxindia/internet-chowkidar/ent/predicate"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sites"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sitescategories"
)

// SitesCategoriesUpdate is the builder for updating SitesCategories entities.
type SitesCategoriesUpdate struct {
	config
	hooks    []Hook
	mutation *SitesCategoriesMutation
}

// Where appends a list predicates to the SitesCategoriesUpdate builder.
func (_u *SitesCategoriesUpdate) Where(ps ...predicate.SitesCategories) *SitesCategoriesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSitesID sets the "sites_id" field.
func (_u *SitesCategoriesUpdate) SetSitesID(v int) *SitesCategoriesUpdate {
	_u.mutation.SetSitesID(v)
	return _u
}

// SetNillableSitesID sets the "sites_id" field if the given value is not nil.
func (_u *SitesCategoriesUpdate) SetNillableSitesID(v *int) *SitesCategoriesUpdate {
	if v != nil {
		_u.SetSitesID(*v)
	}
	return _u
}

// SetCategoriesID sets the "categories_id" field.
func (_u *SitesCategoriesUpdate) SetCategoriesID(v int) *SitesCategoriesUpdate {
	_u.mutation.SetCategoriesID(v)
	return _u
}

// SetNillableCategoriesID sets the "categories_id" field if the given value is not nil.
func (_u *SitesCategoriesUpdate) SetNillableCategoriesID(v *int) *SitesCategoriesUpdate {
	if v != nil {
		_u.SetCategoriesID(*v)
	}
	return _u
}

// SetSites sets the "sites" edge to the Sites entity.
func (_u *SitesCategoriesUpdate) SetSites(v *Sites) *SitesCategoriesUpdate {
	return _u.SetSitesID(v.ID)
}

// SetCategories sets the "categories" edge to the Categories entity.
func (_u *SitesCategoriesUpdate) SetCategories(v *Categories) *SitesCategoriesUpdate {
	return _u.SetCategoriesID(v.ID)
}

// Mutation returns the SitesCategoriesMutation object of the builder.
func (_u *SitesCategoriesUpdate) Mutation() *SitesCategoriesMutation {
	return _u.mutation
}

// ClearSites clears the "sites" edge to the Sites entity.
func (_u *SitesCategoriesUpdate) ClearSites() *SitesCategoriesUpdate {
	_u.mutation.ClearSites()
	return _u
}

// ClearCategories clears the "categories" edge to the Categories entity.
func (_u *SitesCategoriesUpdate) ClearCategories() *SitesCategoriesUpdate {
	_u.mutation.ClearCategories()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SitesCategoriesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SitesCategoriesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SitesCategoriesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SitesCategoriesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SitesCategoriesUpdate) check() error {
	if _u.mutation.SitesCleared() && len(_u.mutation.SitesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SitesCategories.sites"`)
	}
	if _u.mutation.CategoriesCleared() && len(_u.mutation.CategoriesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SitesCategories.categories"`)
	}
	return nil
}

func (_u *SitesCategoriesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sitescategories.Table, sitescategories.Columns, sqlgraph.NewFieldSpec(sitescategories.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitescategories.SitesTable,
			Columns: []string{sitescategories.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitescategories.SitesTable,
			Columns: []string{sitescategories.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitescategories.CategoriesTable,
			Columns: []string{sitescategories.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categories.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitescategories.CategoriesTable,
			Columns: []string{sitescategories.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categories.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sitescategories.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SitesCategoriesUpdateOne is the builder for updating a single SitesCategories entity.
type SitesCategoriesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SitesCategoriesMutation
}

// SetSitesID sets the "sites_id" field.
func (_u *SitesCategoriesUpdateOne) SetSitesID(v int) *SitesCategoriesUpdateOne {
	_u.mutation.SetSitesID(v)
	return _u
}

// SetNillableSitesID sets the "sites_id" field if the given value is not nil.
func (_u *SitesCategoriesUpdateOne) SetNillableSitesID(v *int) *SitesCategoriesUpdateOne {
	if v != nil {
		_u.SetSitesID(*v)
	}
	return _u
}

// SetCategoriesID sets the "categories_id" field.
func (_u *SitesCategoriesUpdateOne) SetCategoriesID(v int) *SitesCategoriesUpdateOne {
	_u.mutation.SetCategoriesID(v)
	return _u
}

// SetNillableCategoriesID sets the "categories_id" field if the given value is not nil.
func (_u *SitesCategoriesUpdateOne) SetNillableCategoriesID(v *int) *SitesCategoriesUpdateOne {
	if v != nil {
		_u.SetCategoriesID(*v)
	}
	return _u
}

// SetSites sets the "sites" edge to the Sites entity.
func (_u *SitesCategoriesUpdateOne) SetSites(v *Sites) *SitesCategoriesUpdateOne {
	return _u.SetSitesID(v.ID)
}

// SetCategories sets the "categories" edge to the Categories entity.
func (_u *SitesCategoriesUpdateOne) SetCategories(v *Categories) *SitesCategoriesUpdateOne {
	return _u.SetCategoriesID(v.ID)
}

// Mutation returns the SitesCategoriesMutation object of the builder.
func (_u *SitesCategoriesUpdateOne) Mutation() *SitesCategoriesMutation {
	return _u.mutation
}

// ClearSites clears the "sites" edge to the Sites entity.
func (_u *SitesCategoriesUpdateOne) ClearSites() *SitesCategoriesUpdateOne {
	_u.mutation.ClearSites()
	return _u
}

// ClearCategories clears the "categories" edge to the Categories entity.
func (_u *SitesCategoriesUpdateOne) ClearCategories() *SitesCategoriesUpdateOne {
	_u.mutation.ClearCategories()
	return _u
}

// Where appends a list predicates to the SitesCategoriesUpdate builder.
func (_u *SitesCategoriesUpdateOne) Where(ps ...predicate.SitesCategories) *SitesCategoriesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SitesCategoriesUpdateOne) Select(field string, fields ...string) *SitesCategoriesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SitesCategories entity.
func (_u *SitesCategoriesUpdateOne) Save(ctx context.Context) (*SitesCategories, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SitesCategoriesUpdateOne) SaveX(ctx context.Context) *SitesCategories {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SitesCategoriesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SitesCategoriesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SitesCategoriesUpdateOne) check() error {
	if _u.mutation.SitesCleared() && len(_u.mutation.SitesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SitesCategories.sites"`)
	}
	if _u.mutation.CategoriesCleared() && len(_u.mutation.CategoriesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SitesCategories.categories"`)
	}
	return nil
}

func (_u *SitesCategoriesUpdateOne) sqlSave(ctx context.Context) (_node *SitesCategories, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sitescategories.Table, sitescategories.Columns, sqlgraph.NewFieldSpec(sitescategories.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SitesCategories.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sitescategories.FieldID)
		for _, f := range fields {
			if !sitescategories.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sitescategories.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitescategories.SitesTable,
			Columns: []string{sitescategories.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitescategories.SitesTable,
			Columns: []string{sitescategories.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitescategories.CategoriesTable,
			Columns: []string{sitescategories.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categories.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitescategories.CategoriesTable,
			Columns: []string{sitescategories.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categories.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SitesCategories{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sitescategories.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
