// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gnulinuxindia/internet-chowkidar/ent/blocks"
	"github.com/gnulinuxindia/internet-chowkidar/ent/categories"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sites"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sitescategories"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sitesuggestions"
)

// SitesCreate is the builder for creating a Sites entity.
type SitesCreate struct {
	config
	mutation *SitesMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SitesCreate) SetCreatedAt(v time.Time) *SitesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SitesCreate) SetNillableCreatedAt(v *time.Time) *SitesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SitesCreate) SetUpdatedAt(v time.Time) *SitesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SitesCreate) SetNillableUpdatedAt(v *time.Time) *SitesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDomain sets the "domain" field.
func (_c *SitesCreate) SetDomain(v string) *SitesCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetPingURL sets the "ping_url" field.
func (_c *SitesCreate) SetPingURL(v string) *SitesCreate {
	_c.mutation.SetPingURL(v)
	return _c
}

// AddBlockIDs adds the "blocks" edge to the Blocks entity by IDs.
func (_c *SitesCreate) AddBlockIDs(ids ...int) *SitesCreate {
	_c.mutation.AddBlockIDs(ids...)
	return _c
}

// AddBlocks adds the "blocks" edges to the Blocks entity.
func (_c *SitesCreate) AddBlocks(v ...*Blocks) *SitesCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBlockIDs(ids...)
}

// AddSitesuggestionIDs adds the "sitesuggestions" edge to the SiteSuggestions entity by IDs.
func (_c *SitesCreate) AddSitesuggestionIDs(ids ...int) *SitesCreate {
	_c.mutation.AddSitesuggestionIDs(ids...)
	return _c
}

// AddSitesuggestions adds the "sitesuggestions" edges to the SiteSuggestions entity.
func (_c *SitesCreate) AddSitesuggestions(v ...*SiteSuggestions) *SitesCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSitesuggestionIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Categories entity by IDs.
func (_c *SitesCreate) AddCategoryIDs(ids ...int) *SitesCreate {
	_c.mutation.AddCategoryIDs(ids...)
	return _c
}

// AddCategories adds the "categories" edges to the Categories entity.
func (_c *SitesCreate) AddCategories(v ...*Categories) *SitesCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCategoryIDs(ids...)
}

// AddSitesCategoryIDs adds the "sites_categories" edge to the SitesCategories entity by IDs.
func (_c *SitesCreate) AddSitesCategoryIDs(ids ...int) *SitesCreate {
	_c.mutation.AddSitesCategoryIDs(ids...)
	return _c
}

// AddSitesCategories adds the "sites_categories" edges to the SitesCategories entity.
func (_c *SitesCreate) AddSitesCategories(v ...*SitesCategories) *SitesCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSitesCategoryIDs(ids...)
}

// Mutation returns the SitesMutation object of the builder.
func (_c *SitesCreate) Mutation() *SitesMutation {
	return _c.mutation
}

// Save creates the Sites in the database.
func (_c *SitesCreate) Save(ctx context.Context) (*Sites, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SitesCreate) SaveX(ctx context.Context) *Sites {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SitesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SitesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SitesCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sites.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sites.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SitesCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Sites.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Sites.updated_at"`)}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Sites.domain"`)}
	}
	if _, ok := _c.mutation.PingURL(); !ok {
		return &ValidationError{Name: "ping_url", err: errors.New(`ent: missing required field "Sites.ping_url"`)}
	}
	return nil
}

func (_c *SitesCreate) sqlSave(ctx context.Context) (*Sites, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SitesCreate) createSpec() (*Sites, *sqlgraph.CreateSpec) {
	var (
		_node = &Sites{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sites.Table, sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sites.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sites.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(sites.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.PingURL(); ok {
		_spec.SetField(sites.FieldPingURL, field.TypeString, value)
		_node.PingURL = value
	}
	if nodes := _c.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sites.BlocksTable,
			Columns: []string{sites.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blocks.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SitesuggestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sites.SitesuggestionsTable,
			Columns: []string{sites.SitesuggestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitesuggestions.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sites.CategoriesTable,
			Columns: sites.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categories.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SitesCategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   sites.SitesCategoriesTable,
			Columns: []string{sites.SitesCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitescategories.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SitesCreateBulk is the builder for creating many Sites entities in bulk.
type SitesCreateBulk struct {
	config
	err      error
	builders []*SitesCreate
}

// Save creates the Sites entities in the database.
func (_c *SitesCreateBulk) Save(ctx context.Context) ([]*Sites, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Sites, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SitesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SitesCreateBulk) SaveX(ctx context.Context) []*Sites {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SitesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SitesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
