// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gnulinuxindia/internet-chowkidar/ent/predicate"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sites"
)

// SitesUpdate is the builder for updating Sites entities.
type SitesUpdate struct {
	config
	hooks    []Hook
	mutation *SitesMutation
}

// Where appends a list predicates to the SitesUpdate builder.
func (su *SitesUpdate) Where(ps ...predicate.Sites) *SitesUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SitesUpdate) SetUpdatedAt(t time.Time) *SitesUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetDomain sets the "domain" field.
func (su *SitesUpdate) SetDomain(s string) *SitesUpdate {
	su.mutation.SetDomain(s)
	return su
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (su *SitesUpdate) SetNillableDomain(s *string) *SitesUpdate {
	if s != nil {
		su.SetDomain(*s)
	}
	return su
}

// Mutation returns the SitesMutation object of the builder.
func (su *SitesUpdate) Mutation() *SitesMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SitesUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SitesUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SitesUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SitesUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SitesUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := sites.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

func (su *SitesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sites.Table, sites.Columns, sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(sites.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.Domain(); ok {
		_spec.SetField(sites.FieldDomain, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sites.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SitesUpdateOne is the builder for updating a single Sites entity.
type SitesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SitesMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SitesUpdateOne) SetUpdatedAt(t time.Time) *SitesUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetDomain sets the "domain" field.
func (suo *SitesUpdateOne) SetDomain(s string) *SitesUpdateOne {
	suo.mutation.SetDomain(s)
	return suo
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (suo *SitesUpdateOne) SetNillableDomain(s *string) *SitesUpdateOne {
	if s != nil {
		suo.SetDomain(*s)
	}
	return suo
}

// Mutation returns the SitesMutation object of the builder.
func (suo *SitesUpdateOne) Mutation() *SitesMutation {
	return suo.mutation
}

// Where appends a list predicates to the SitesUpdate builder.
func (suo *SitesUpdateOne) Where(ps ...predicate.Sites) *SitesUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SitesUpdateOne) Select(field string, fields ...string) *SitesUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Sites entity.
func (suo *SitesUpdateOne) Save(ctx context.Context) (*Sites, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SitesUpdateOne) SaveX(ctx context.Context) *Sites {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SitesUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SitesUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SitesUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := sites.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

func (suo *SitesUpdateOne) sqlSave(ctx context.Context) (_node *Sites, err error) {
	_spec := sqlgraph.NewUpdateSpec(sites.Table, sites.Columns, sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sites.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sites.FieldID)
		for _, f := range fields {
			if !sites.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sites.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(sites.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.Domain(); ok {
		_spec.SetField(sites.FieldDomain, field.TypeString, value)
	}
	_node = &Sites{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sites.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
