// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gnulinuxindia/internet-chowkidar/ent/blocks"
	"github.com/gnulinuxindia/internet-chowkidar/ent/categories"
	"github.com/gnulinuxindia/internet-chowkidar/ent/predicate"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sites"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sitescategories"
)

// SitesQuery is the builder for querying Sites entities.
type SitesQuery struct {
	config
	ctx                 *QueryContext
	order               []sites.OrderOption
	inters              []Interceptor
	predicates          []predicate.Sites
	withBlocks          *BlocksQuery
	withCategories      *CategoriesQuery
	withSitesCategories *SitesCategoriesQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SitesQuery builder.
func (_q *SitesQuery) Where(ps ...predicate.Sites) *SitesQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SitesQuery) Limit(limit int) *SitesQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SitesQuery) Offset(offset int) *SitesQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SitesQuery) Unique(unique bool) *SitesQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SitesQuery) Order(o ...sites.OrderOption) *SitesQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryBlocks chains the current query on the "blocks" edge.
func (_q *SitesQuery) QueryBlocks() *BlocksQuery {
	query := (&BlocksClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sites.Table, sites.FieldID, selector),
			sqlgraph.To(blocks.Table, blocks.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, sites.BlocksTable, sites.BlocksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCategories chains the current query on the "categories" edge.
func (_q *SitesQuery) QueryCategories() *CategoriesQuery {
	query := (&CategoriesClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sites.Table, sites.FieldID, selector),
			sqlgraph.To(categories.Table, categories.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, sites.CategoriesTable, sites.CategoriesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySitesCategories chains the current query on the "sites_categories" edge.
func (_q *SitesQuery) QuerySitesCategories() *SitesCategoriesQuery {
	query := (&SitesCategoriesClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sites.Table, sites.FieldID, selector),
			sqlgraph.To(sitescategories.Table, sitescategories.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, sites.SitesCategoriesTable, sites.SitesCategoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Sites entity from the query.
// Returns a *NotFoundError when no Sites was found.
func (_q *SitesQuery) First(ctx context.Context) (*Sites, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sites.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SitesQuery) FirstX(ctx context.Context) *Sites {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Sites ID from the query.
// Returns a *NotFoundError when no Sites ID was found.
func (_q *SitesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sites.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SitesQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Sites entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Sites entity is found.
// Returns a *NotFoundError when no Sites entities are found.
func (_q *SitesQuery) Only(ctx context.Context) (*Sites, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sites.Label}
	default:
		return nil, &NotSingularError{sites.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SitesQuery) OnlyX(ctx context.Context) *Sites {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Sites ID in the query.
// Returns a *NotSingularError when more than one Sites ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SitesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sites.Label}
	default:
		err = &NotSingularError{sites.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SitesQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SitesSlice.
func (_q *SitesQuery) All(ctx context.Context) ([]*Sites, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Sites, *SitesQuery]()
	return withInterceptors[[]*Sites](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SitesQuery) AllX(ctx context.Context) []*Sites {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Sites IDs.
func (_q *SitesQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(sites.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SitesQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SitesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SitesQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SitesQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SitesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SitesQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SitesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SitesQuery) Clone() *SitesQuery {
	if _q == nil {
		return nil
	}
	return &SitesQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]sites.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.Sites{}, _q.predicates...),
		withBlocks:          _q.withBlocks.Clone(),
		withCategories:      _q.withCategories.Clone(),
		withSitesCategories: _q.withSitesCategories.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithBlocks tells the query-builder to eager-load the nodes that are connected to
// the "blocks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SitesQuery) WithBlocks(opts ...func(*BlocksQuery)) *SitesQuery {
	query := (&BlocksClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBlocks = query
	return _q
}

// WithCategories tells the query-builder to eager-load the nodes that are connected to
// the "categories" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SitesQuery) WithCategories(opts ...func(*CategoriesQuery)) *SitesQuery {
	query := (&CategoriesClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCategories = query
	return _q
}

// WithSitesCategories tells the query-builder to eager-load the nodes that are connected to
// the "sites_categories" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SitesQuery) WithSitesCategories(opts ...func(*SitesCategoriesQuery)) *SitesQuery {
	query := (&SitesCategoriesClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSitesCategories = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Sites.Query().
//		GroupBy(sites.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SitesQuery) GroupBy(field string, fields ...string) *SitesGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SitesGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = sites.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Sites.Query().
//		Select(sites.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *SitesQuery) Select(fields ...string) *SitesSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SitesSelect{SitesQuery: _q}
	sbuild.label = sites.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SitesSelect configured with the given aggregations.
func (_q *SitesQuery) Aggregate(fns ...AggregateFunc) *SitesSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SitesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !sites.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SitesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Sites, error) {
	var (
		nodes       = []*Sites{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withBlocks != nil,
			_q.withCategories != nil,
			_q.withSitesCategories != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Sites).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Sites{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withBlocks; query != nil {
		if err := _q.loadBlocks(ctx, query, nodes,
			func(n *Sites) { n.Edges.Blocks = []*Blocks{} },
			func(n *Sites, e *Blocks) { n.Edges.Blocks = append(n.Edges.Blocks, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCategories; query != nil {
		if err := _q.loadCategories(ctx, query, nodes,
			func(n *Sites) { n.Edges.Categories = []*Categories{} },
			func(n *Sites, e *Categories) { n.Edges.Categories = append(n.Edges.Categories, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSitesCategories; query != nil {
		if err := _q.loadSitesCategories(ctx, query, nodes,
			func(n *Sites) { n.Edges.SitesCategories = []*SitesCategories{} },
			func(n *Sites, e *SitesCategories) { n.Edges.SitesCategories = append(n.Edges.SitesCategories, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SitesQuery) loadBlocks(ctx context.Context, query *BlocksQuery, nodes []*Sites, init func(*Sites), assign func(*Sites, *Blocks)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Sites)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(blocks.FieldSiteID)
	}
	query.Where(predicate.Blocks(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(sites.BlocksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SiteID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "site_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *SitesQuery) loadCategories(ctx context.Context, query *CategoriesQuery, nodes []*Sites, init func(*Sites), assign func(*Sites, *Categories)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Sites)
	nids := make(map[int]map[*Sites]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(sites.CategoriesTable)
		s.Join(joinT).On(s.C(categories.FieldID), joinT.C(sites.CategoriesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(sites.CategoriesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(sites.CategoriesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Sites]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Categories](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "categories" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *SitesQuery) loadSitesCategories(ctx context.Context, query *SitesCategoriesQuery, nodes []*Sites, init func(*Sites), assign func(*Sites, *SitesCategories)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Sites)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(sitescategories.FieldSitesID)
	}
	query.Where(predicate.SitesCategories(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(sites.SitesCategoriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SitesID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "sites_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SitesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SitesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sites.Table, sites.Columns, sqlgraph.NewFieldSpec(sites.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sites.FieldID)
		for i := range fields {
			if fields[i] != sites.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SitesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(sites.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = sites.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SitesGroupBy is the group-by builder for Sites entities.
type SitesGroupBy struct {
	selector
	build *SitesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SitesGroupBy) Aggregate(fns ...AggregateFunc) *SitesGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SitesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SitesQuery, *SitesGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SitesGroupBy) sqlScan(ctx context.Context, root *SitesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SitesSelect is the builder for selecting fields of Sites entities.
type SitesSelect struct {
	*SitesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SitesSelect) Aggregate(fns ...AggregateFunc) *SitesSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SitesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SitesQuery, *SitesSelect](ctx, _s.SitesQuery, _s, _s.inters, v)
}

func (_s *SitesSelect) sqlScan(ctx context.Context, root *SitesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
