// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gnulinuxindia/internet-chowkidar/ent/predicate"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sitesuggestions"
)

// SiteSuggestionsDelete is the builder for deleting a SiteSuggestions entity.
type SiteSuggestionsDelete struct {
	config
	hooks    []Hook
	mutation *SiteSuggestionsMutation
}

// Where appends a list predicates to the SiteSuggestionsDelete builder.
func (_d *SiteSuggestionsDelete) Where(ps ...predicate.SiteSuggestions) *SiteSuggestionsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SiteSuggestionsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SiteSuggestionsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SiteSuggestionsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sitesuggestions.Table, sqlgraph.NewFieldSpec(sitesuggestions.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SiteSuggestionsDeleteOne is the builder for deleting a single SiteSuggestions entity.
type SiteSuggestionsDeleteOne struct {
	_d *SiteSuggestionsDelete
}

// Where appends a list predicates to the SiteSuggestionsDelete builder.
func (_d *SiteSuggestionsDeleteOne) Where(ps ...predicate.SiteSuggestions) *SiteSuggestionsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SiteSuggestionsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sitesuggestions.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SiteSuggestionsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
