// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gnulinuxindia/internet-chowkidar/ent/categories"
	"github.com/gnulinuxindia/internet-chowkidar/ent/predicate"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sites"
	"github.com/gnulinuxindia/internet-chowkidar/ent/sitescategories"
)

// SitesCategoriesQuery is the builder for querying SitesCategories entities.
type SitesCategoriesQuery struct {
	config
	ctx            *QueryContext
	order          []sitescategories.OrderOption
	inters         []Interceptor
	predicates     []predicate.SitesCategories
	withSites      *SitesQuery
	withCategories *CategoriesQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SitesCategoriesQuery builder.
func (scq *SitesCategoriesQuery) Where(ps ...predicate.SitesCategories) *SitesCategoriesQuery {
	scq.predicates = append(scq.predicates, ps...)
	return scq
}

// Limit the number of records to be returned by this query.
func (scq *SitesCategoriesQuery) Limit(limit int) *SitesCategoriesQuery {
	scq.ctx.Limit = &limit
	return scq
}

// Offset to start from.
func (scq *SitesCategoriesQuery) Offset(offset int) *SitesCategoriesQuery {
	scq.ctx.Offset = &offset
	return scq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (scq *SitesCategoriesQuery) Unique(unique bool) *SitesCategoriesQuery {
	scq.ctx.Unique = &unique
	return scq
}

// Order specifies how the records should be ordered.
func (scq *SitesCategoriesQuery) Order(o ...sitescategories.OrderOption) *SitesCategoriesQuery {
	scq.order = append(scq.order, o...)
	return scq
}

// QuerySites chains the current query on the "sites" edge.
func (scq *SitesCategoriesQuery) QuerySites() *SitesQuery {
	query := (&SitesClient{config: scq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := scq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := scq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sitescategories.Table, sitescategories.FieldID, selector),
			sqlgraph.To(sites.Table, sites.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sitescategories.SitesTable, sitescategories.SitesColumn),
		)
		fromU = sqlgraph.SetNeighbors(scq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCategories chains the current query on the "categories" edge.
func (scq *SitesCategoriesQuery) QueryCategories() *CategoriesQuery {
	query := (&CategoriesClient{config: scq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := scq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := scq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sitescategories.Table, sitescategories.FieldID, selector),
			sqlgraph.To(categories.Table, categories.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, sitescategories.CategoriesTable, sitescategories.CategoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(scq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SitesCategories entity from the query.
// Returns a *NotFoundError when no SitesCategories was found.
func (scq *SitesCategoriesQuery) First(ctx context.Context) (*SitesCategories, error) {
	nodes, err := scq.Limit(1).All(setContextOp(ctx, scq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sitescategories.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (scq *SitesCategoriesQuery) FirstX(ctx context.Context) *SitesCategories {
	node, err := scq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SitesCategories ID from the query.
// Returns a *NotFoundError when no SitesCategories ID was found.
func (scq *SitesCategoriesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = scq.Limit(1).IDs(setContextOp(ctx, scq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sitescategories.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (scq *SitesCategoriesQuery) FirstIDX(ctx context.Context) int {
	id, err := scq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SitesCategories entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SitesCategories entity is found.
// Returns a *NotFoundError when no SitesCategories entities are found.
func (scq *SitesCategoriesQuery) Only(ctx context.Context) (*SitesCategories, error) {
	nodes, err := scq.Limit(2).All(setContextOp(ctx, scq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sitescategories.Label}
	default:
		return nil, &NotSingularError{sitescategories.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (scq *SitesCategoriesQuery) OnlyX(ctx context.Context) *SitesCategories {
	node, err := scq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SitesCategories ID in the query.
// Returns a *NotSingularError when more than one SitesCategories ID is found.
// Returns a *NotFoundError when no entities are found.
func (scq *SitesCategoriesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = scq.Limit(2).IDs(setContextOp(ctx, scq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sitescategories.Label}
	default:
		err = &NotSingularError{sitescategories.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (scq *SitesCategoriesQuery) OnlyIDX(ctx context.Context) int {
	id, err := scq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SitesCategoriesSlice.
func (scq *SitesCategoriesQuery) All(ctx context.Context) ([]*SitesCategories, error) {
	ctx = setContextOp(ctx, scq.ctx, "All")
	if err := scq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SitesCategories, *SitesCategoriesQuery]()
	return withInterceptors[[]*SitesCategories](ctx, scq, qr, scq.inters)
}

// AllX is like All, but panics if an error occurs.
func (scq *SitesCategoriesQuery) AllX(ctx context.Context) []*SitesCategories {
	nodes, err := scq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SitesCategories IDs.
func (scq *SitesCategoriesQuery) IDs(ctx context.Context) (ids []int, err error) {
	if scq.ctx.Unique == nil && scq.path != nil {
		scq.Unique(true)
	}
	ctx = setContextOp(ctx, scq.ctx, "IDs")
	if err = scq.Select(sitescategories.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (scq *SitesCategoriesQuery) IDsX(ctx context.Context) []int {
	ids, err := scq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (scq *SitesCategoriesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, scq.ctx, "Count")
	if err := scq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, scq, querierCount[*SitesCategoriesQuery](), scq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (scq *SitesCategoriesQuery) CountX(ctx context.Context) int {
	count, err := scq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (scq *SitesCategoriesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, scq.ctx, "Exist")
	switch _, err := scq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (scq *SitesCategoriesQuery) ExistX(ctx context.Context) bool {
	exist, err := scq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SitesCategoriesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (scq *SitesCategoriesQuery) Clone() *SitesCategoriesQuery {
	if scq == nil {
		return nil
	}
	return &SitesCategoriesQuery{
		config:         scq.config,
		ctx:            scq.ctx.Clone(),
		order:          append([]sitescategories.OrderOption{}, scq.order...),
		inters:         append([]Interceptor{}, scq.inters...),
		predicates:     append([]predicate.SitesCategories{}, scq.predicates...),
		withSites:      scq.withSites.Clone(),
		withCategories: scq.withCategories.Clone(),
		// clone intermediate query.
		sql:  scq.sql.Clone(),
		path: scq.path,
	}
}

// WithSites tells the query-builder to eager-load the nodes that are connected to
// the "sites" edge. The optional arguments are used to configure the query builder of the edge.
func (scq *SitesCategoriesQuery) WithSites(opts ...func(*SitesQuery)) *SitesCategoriesQuery {
	query := (&SitesClient{config: scq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	scq.withSites = query
	return scq
}

// WithCategories tells the query-builder to eager-load the nodes that are connected to
// the "categories" edge. The optional arguments are used to configure the query builder of the edge.
func (scq *SitesCategoriesQuery) WithCategories(opts ...func(*CategoriesQuery)) *SitesCategoriesQuery {
	query := (&CategoriesClient{config: scq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	scq.withCategories = query
	return scq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SitesID int `json:"sites_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SitesCategories.Query().
//		GroupBy(sitescategories.FieldSitesID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (scq *SitesCategoriesQuery) GroupBy(field string, fields ...string) *SitesCategoriesGroupBy {
	scq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SitesCategoriesGroupBy{build: scq}
	grbuild.flds = &scq.ctx.Fields
	grbuild.label = sitescategories.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SitesID int `json:"sites_id,omitempty"`
//	}
//
//	client.SitesCategories.Query().
//		Select(sitescategories.FieldSitesID).
//		Scan(ctx, &v)
func (scq *SitesCategoriesQuery) Select(fields ...string) *SitesCategoriesSelect {
	scq.ctx.Fields = append(scq.ctx.Fields, fields...)
	sbuild := &SitesCategoriesSelect{SitesCategoriesQuery: scq}
	sbuild.label = sitescategories.Label
	sbuild.flds, sbuild.scan = &scq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SitesCategoriesSelect configured with the given aggregations.
func (scq *SitesCategoriesQuery) Aggregate(fns ...AggregateFunc) *SitesCategoriesSelect {
	return scq.Select().Aggregate(fns...)
}

func (scq *SitesCategoriesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range scq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, scq); err != nil {
				return err
			}
		}
	}
	for _, f := range scq.ctx.Fields {
		if !sitescategories.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if scq.path != nil {
		prev, err := scq.path(ctx)
		if err != nil {
			return err
		}
		scq.sql = prev
	}
	return nil
}

func (scq *SitesCategoriesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SitesCategories, error) {
	var (
		nodes       = []*SitesCategories{}
		_spec       = scq.querySpec()
		loadedTypes = [2]bool{
			scq.withSites != nil,
			scq.withCategories != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SitesCategories).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SitesCategories{config: scq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, scq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := scq.withSites; query != nil {
		if err := scq.loadSites(ctx, query, nodes, nil,
			func(n *SitesCategories, e *Sites) { n.Edges.Sites = e }); err != nil {
			return nil, err
		}
	}
	if query := scq.withCategories; query != nil {
		if err := scq.loadCategories(ctx, query, nodes, nil,
			func(n *SitesCategories, e *Categories) { n.Edges.Categories = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (scq *SitesCategoriesQuery) loadSites(ctx context.Context, query *SitesQuery, nodes []*SitesCategories, init func(*SitesCategories), assign func(*SitesCategories, *Sites)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SitesCategories)
	for i := range nodes {
		fk := nodes[i].SitesID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sites.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sites_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (scq *SitesCategoriesQuery) loadCategories(ctx context.Context, query *CategoriesQuery, nodes []*SitesCategories, init func(*SitesCategories), assign func(*SitesCategories, *Categories)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SitesCategories)
	for i := range nodes {
		fk := nodes[i].CategoriesID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(categories.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "categories_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (scq *SitesCategoriesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := scq.querySpec()
	_spec.Node.Columns = scq.ctx.Fields
	if len(scq.ctx.Fields) > 0 {
		_spec.Unique = scq.ctx.Unique != nil && *scq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, scq.driver, _spec)
}

func (scq *SitesCategoriesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sitescategories.Table, sitescategories.Columns, sqlgraph.NewFieldSpec(sitescategories.FieldID, field.TypeInt))
	_spec.From = scq.sql
	if unique := scq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if scq.path != nil {
		_spec.Unique = true
	}
	if fields := scq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sitescategories.FieldID)
		for i := range fields {
			if fields[i] != sitescategories.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if scq.withSites != nil {
			_spec.Node.AddColumnOnce(sitescategories.FieldSitesID)
		}
		if scq.withCategories != nil {
			_spec.Node.AddColumnOnce(sitescategories.FieldCategoriesID)
		}
	}
	if ps := scq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := scq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := scq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := scq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (scq *SitesCategoriesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(scq.driver.Dialect())
	t1 := builder.Table(sitescategories.Table)
	columns := scq.ctx.Fields
	if len(columns) == 0 {
		columns = sitescategories.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if scq.sql != nil {
		selector = scq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if scq.ctx.Unique != nil && *scq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range scq.predicates {
		p(selector)
	}
	for _, p := range scq.order {
		p(selector)
	}
	if offset := scq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := scq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SitesCategoriesGroupBy is the group-by builder for SitesCategories entities.
type SitesCategoriesGroupBy struct {
	selector
	build *SitesCategoriesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (scgb *SitesCategoriesGroupBy) Aggregate(fns ...AggregateFunc) *SitesCategoriesGroupBy {
	scgb.fns = append(scgb.fns, fns...)
	return scgb
}

// Scan applies the selector query and scans the result into the given value.
func (scgb *SitesCategoriesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scgb.build.ctx, "GroupBy")
	if err := scgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SitesCategoriesQuery, *SitesCategoriesGroupBy](ctx, scgb.build, scgb, scgb.build.inters, v)
}

func (scgb *SitesCategoriesGroupBy) sqlScan(ctx context.Context, root *SitesCategoriesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(scgb.fns))
	for _, fn := range scgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*scgb.flds)+len(scgb.fns))
		for _, f := range *scgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*scgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SitesCategoriesSelect is the builder for selecting fields of SitesCategories entities.
type SitesCategoriesSelect struct {
	*SitesCategoriesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (scs *SitesCategoriesSelect) Aggregate(fns ...AggregateFunc) *SitesCategoriesSelect {
	scs.fns = append(scs.fns, fns...)
	return scs
}

// Scan applies the selector query and scans the result into the given value.
func (scs *SitesCategoriesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scs.ctx, "Select")
	if err := scs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SitesCategoriesQuery, *SitesCategoriesSelect](ctx, scs.SitesCategoriesQuery, scs, scs.inters, v)
}

func (scs *SitesCategoriesSelect) sqlScan(ctx context.Context, root *SitesCategoriesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(scs.fns))
	for _, fn := range scs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*scs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
