// Code generated by tools/update-providers.go; DO NOT EDIT.
package service

import "github.com/gnulinuxindia/internet-chowkidar/pkg/domain/repository"

func ProvideIspService(
	repo repository.IspRepository,
) IspService {
	return &ispServiceImpl{
		repo: repo,
	}
}

func ProvideSitesService(
	repo repository.SitesRepository,
) SitesService {
	return &sitesServiceImpl{
		repo: repo,
	}
}
