// Code generated by tools/update-providers.go; DO NOT EDIT.
package di

import (
	"github.com/gnulinuxindia/internet-chowkidar/pkg/domain/repository"
	"github.com/google/wire"
)

type Repositories struct {
	repository.CounterRepository
}

var RepositorySet = wire.NewSet(
	repository.ProvideCounterRepository,
	wire.Struct(new(Repositories), "*"),
)

var MockRepositorySet = wire.NewSet(
	repository.ProvideCounterRepository,
	wire.Struct(new(Repositories), "*"),
)
