// Code generated by tools/update-providers.go; DO NOT EDIT.
package di

import (
	"github.com/gnulinuxindia/internet-chowkidar/pkg/domain/service"
	mock_service "github.com/gnulinuxindia/internet-chowkidar/pkg/domain/service/mock"
	"github.com/golang/mock/gomock"
	"github.com/google/wire"
)

type Services struct {
	service.CounterService
	service.EmailService
}

var ServiceSet = wire.NewSet(
	service.ProvideCounterService,
	service.ProvideEmailService,
	wire.Struct(new(Services), "*"),
)

func ProvideMockEmailService(ctrl *gomock.Controller) service.EmailService {
	return mock_service.NewMockEmailService(ctrl)
}

var MockServiceSet = wire.NewSet(
	service.ProvideCounterService,
	ProvideMockEmailService,
	wire.Struct(new(Services), "*"),
)
