// Code generated by tools/update-providers.go; DO NOT EDIT.
package api

import (
	"github.com/gnulinuxindia/internet-chowkidar/api/handler"
	"github.com/google/wire"
)

type Handlers struct {
	handler.BlocksHandler
	handler.CategoryHandler
	handler.ApiDocsHandler
	handler.HealthHandler
	handler.IspHandler
	handler.ReportsHandler
	handler.SecurityHandler
	handler.SitesHandler
}

type MockHandlers struct {
}

var HandlerSet = wire.NewSet(
	handler.ProvideBlocksHandler,
	handler.ProvideCategoryHandler,
	handler.ProvideApiDocsHandler,
	handler.ProvideHealthHandler,
	handler.ProvideIspHandler,
	handler.ProvideReportsHandler,
	handler.ProvideSecurityHandler,
	handler.ProvideSitesHandler,
	wire.Struct(new(Handlers), "*"),
)

var MockHandlersInstance MockHandlers = MockHandlers{}

var MockHandlerSet = wire.NewSet(
	handler.ProvideBlocksHandler,
	handler.ProvideCategoryHandler,
	handler.ProvideApiDocsHandler,
	handler.ProvideHealthHandler,
	handler.ProvideIspHandler,
	handler.ProvideReportsHandler,
	handler.ProvideSecurityHandler,
	handler.ProvideSitesHandler,
	wire.Struct(new(Handlers), "*"),
	wire.Struct(new(MockHandlers), "*"),
)
