// Code generated by tools/update-providers.go; DO NOT EDIT.
package api

import (
	"github.com/gnulinuxindia/internet-chowkidar/api/handler"
	"github.com/google/wire"
)

type Handlers struct {
	handler.CounterHandler
}

type MockHandlers struct {
}

var HandlerSet = wire.NewSet(
	handler.ProvideCounterHandler,
	wire.Struct(new(Handlers), "*"),
)

var MockHandlersInstance MockHandlers = MockHandlers{}

var MockHandlerSet = wire.NewSet(
	handler.ProvideCounterHandler,
	wire.Struct(new(Handlers), "*"),
	wire.Struct(new(MockHandlers), "*"),
)
